language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libatlas-base-dev
      - libfftw3-dev

before_install:
  - pip install codecov
  - git clone https://github.com/arrayfire/arrayfire
  - cd arrayfire && mkdir build && cd build 
  - cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DBUILD_CPU=ON -DBUILD_CUDA=OFF -DBUILD_GRAPHICS=OFF -DBUILD_OPENCL=OFF -DBUILD_TEST=OFF .. 
  - make
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$PWD/lib
  
install:
  - pip install numpy
  - pip install arrayfire

after_success:
  - codecov

script: py.test
